### ISSUE TITLE
shutil not working without initializing os

### ISSUE THREAD

**Issue by pankajr141** [pankajr141/libs3#4]
```  
from libs3 import shutil
shutil.authorize(bucket, aws_access_key_id, aws_secret_access_key)
shutil.copy("/dumps/bse_codes_equity.csv", path, download=True)
```

Error:
```
Traceback (most recent call last):
  File "stratergy/nav_stocks.py", line 30, in <module>
    path = download_meta()
  File "stratergy/nav_stocks.py", line 17, in download_meta
    shutil.copy("/dumps/detail/%s" % (datetime.now().strftime("%d_%m_%Y") + ".json"), os.path.join(path, "mf.json"), download=True)
  File "/home/ec2-user/env/funds/lib64/python3.7/site-packages/libs3/shutil.py", line 50, in copy
    if not self.os.path.exists(src):
  File "/home/ec2-user/env/funds/lib64/python3.7/site-packages/libs3/path.py", line 15, in exists
    for bucket_object in self.os_obj.bucket.objects.filter(Prefix=x):
AttributeError: 'OS' object has no attribute 'bucket'
```

**Comment by pankajr141** [comment]
Fixed in 1.2
